name: Install Clang-Format Ubuntu
description: Installs a specific version of clang-format on Ubuntu 20.04 and newer
inputs:
  clang-version:
    description: "Version of Clang-Format to install"
    required: true
    default: "10"

runs:
  using: "composite"
  steps:
    - name: Install Clang-Format
      run: |
        codename=$(lsb_release --codename --short)
        sudo tee /etc/apt/sources.list.d/llvm.list >/dev/null <<EOF
        deb http://apt.llvm.org/${codename}/ llvm-toolchain-${codename}-${{ inputs.clang-version }} main
        deb-src http://apt.llvm.org/${codename}/ llvm-toolchain-${codename}-${{ inputs.clang-version }} main
        EOF
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add
        sudo apt-get update
        sudo apt-get install clang-format-${{ inputs.clang-version }}

        # Verify installation
        clang-format-${{ inputs.clang-version }} --version
      shell: bash
