/* Generated by generate.py from hook/extern.h. Do not edit. */
#include "extern.h"

#define RAW_EXPORT __attribute__((noinline, used))

RAW_EXPORT
int32_t call__g(void)
{
    return _g((uint32_t)0, (uint32_t)1);
}

RAW_EXPORT
int64_t call_accept(void)
{
    return accept((uint32_t)0, (uint32_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_rollback(void)
{
    return rollback((uint32_t)0, (uint32_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_util_raddr(void)
{
    return util_raddr((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_util_accid(void)
{
    return util_accid((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_util_verify(void)
{
    return util_verify((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_util_sha512h(void)
{
    return util_sha512h((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_util_keylet(void)
{
    return util_keylet((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_sto_validate(void)
{
    return sto_validate((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_sto_subfield(void)
{
    return sto_subfield((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_sto_subarray(void)
{
    return sto_subarray((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_sto_emplace(void)
{
    return sto_emplace((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_sto_erase(void)
{
    return sto_erase((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_etxn_burden(void)
{
    return etxn_burden();
}

RAW_EXPORT
int64_t call_etxn_details(void)
{
    return etxn_details((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_etxn_fee_base(void)
{
    return etxn_fee_base((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_etxn_reserve(void)
{
    return etxn_reserve((uint32_t)0);
}

RAW_EXPORT
int64_t call_etxn_generation(void)
{
    return etxn_generation();
}

RAW_EXPORT
int64_t call_etxn_nonce(void)
{
    return etxn_nonce((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_emit(void)
{
    return emit((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_set(void)
{
    return float_set((int32_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_float_multiply(void)
{
    return float_multiply((int64_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_float_mulratio(void)
{
    return float_mulratio((int64_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_negate(void)
{
    return float_negate((int64_t)0);
}

RAW_EXPORT
int64_t call_float_compare(void)
{
    return float_compare((int64_t)0, (int64_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_sum(void)
{
    return float_sum((int64_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_float_sto(void)
{
    return float_sto((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (int64_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_sto_set(void)
{
    return float_sto_set((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_invert(void)
{
    return float_invert((int64_t)0);
}

RAW_EXPORT
int64_t call_float_divide(void)
{
    return float_divide((int64_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_float_one(void)
{
    return float_one();
}

RAW_EXPORT
int64_t call_float_mantissa(void)
{
    return float_mantissa((int64_t)0);
}

RAW_EXPORT
int64_t call_float_sign(void)
{
    return float_sign((int64_t)0);
}

RAW_EXPORT
int64_t call_float_int(void)
{
    return float_int((int64_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_float_log(void)
{
    return float_log((int64_t)0);
}

RAW_EXPORT
int64_t call_float_root(void)
{
    return float_root((int64_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_fee_base(void)
{
    return fee_base();
}

RAW_EXPORT
int64_t call_ledger_seq(void)
{
    return ledger_seq();
}

RAW_EXPORT
int64_t call_ledger_last_time(void)
{
    return ledger_last_time();
}

RAW_EXPORT
int64_t call_ledger_last_hash(void)
{
    return ledger_last_hash((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_ledger_nonce(void)
{
    return ledger_nonce((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_ledger_keylet(void)
{
    return ledger_keylet((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_hook_account(void)
{
    return hook_account((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_hook_hash(void)
{
    return hook_hash((uint32_t)0, (uint32_t)0, (int32_t)0);
}

RAW_EXPORT
int64_t call_hook_param_set(void)
{
    return hook_param_set((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_hook_param(void)
{
    return hook_param((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_hook_again(void)
{
    return hook_again();
}

RAW_EXPORT
int64_t call_hook_skip(void)
{
    return hook_skip((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_hook_pos(void)
{
    return hook_pos();
}

RAW_EXPORT
int64_t call_slot(void)
{
    return slot((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_clear(void)
{
    return slot_clear((uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_count(void)
{
    return slot_count((uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_set(void)
{
    return slot_set((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_size(void)
{
    return slot_size((uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_subarray(void)
{
    return slot_subarray((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_subfield(void)
{
    return slot_subfield((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_type(void)
{
    return slot_type((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_slot_float(void)
{
    return slot_float((uint32_t)0);
}

RAW_EXPORT
int64_t call_state_set(void)
{
    return state_set((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_state_foreign_set(void)
{
    return state_foreign_set((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_state(void)
{
    return state((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_state_foreign(void)
{
    return state_foreign((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_trace(void)
{
    return trace((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_trace_num(void)
{
    return trace_num((uint32_t)0, (uint32_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_trace_float(void)
{
    return trace_float((uint32_t)0, (uint32_t)0, (int64_t)0);
}

RAW_EXPORT
int64_t call_otxn_burden(void)
{
    return otxn_burden();
}

RAW_EXPORT
int64_t call_otxn_field(void)
{
    return otxn_field((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_otxn_generation(void)
{
    return otxn_generation();
}

RAW_EXPORT
int64_t call_otxn_id(void)
{
    return otxn_id((uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_otxn_type(void)
{
    return otxn_type();
}

RAW_EXPORT
int64_t call_otxn_slot(void)
{
    return otxn_slot((uint32_t)0);
}

RAW_EXPORT
int64_t call_otxn_param(void)
{
    return otxn_param((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_meta_slot(void)
{
    return meta_slot((uint32_t)0);
}

RAW_EXPORT
int64_t call_xpop_slot(void)
{
    return xpop_slot((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t call_prepare(void)
{
    return prepare((uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int32_t call__g_rollback(void)
{
    return _g((uint32_t)0, (uint32_t)0);
}

RAW_EXPORT
int64_t hook(uint32_t selector)
{
    switch (selector)
    {
        case 0: return call__g();
        case 1: return call_accept();
        case 2: return call_rollback();
        case 3: return call_util_raddr();
        case 4: return call_util_accid();
        case 5: return call_util_verify();
        case 6: return call_util_sha512h();
        case 7: return call_util_keylet();
        case 8: return call_sto_validate();
        case 9: return call_sto_subfield();
        case 10: return call_sto_subarray();
        case 11: return call_sto_emplace();
        case 12: return call_sto_erase();
        case 13: return call_etxn_burden();
        case 14: return call_etxn_details();
        case 15: return call_etxn_fee_base();
        case 16: return call_etxn_reserve();
        case 17: return call_etxn_generation();
        case 18: return call_etxn_nonce();
        case 19: return call_emit();
        case 20: return call_float_set();
        case 21: return call_float_multiply();
        case 22: return call_float_mulratio();
        case 23: return call_float_negate();
        case 24: return call_float_compare();
        case 25: return call_float_sum();
        case 26: return call_float_sto();
        case 27: return call_float_sto_set();
        case 28: return call_float_invert();
        case 29: return call_float_divide();
        case 30: return call_float_one();
        case 31: return call_float_mantissa();
        case 32: return call_float_sign();
        case 33: return call_float_int();
        case 34: return call_float_log();
        case 35: return call_float_root();
        case 36: return call_fee_base();
        case 37: return call_ledger_seq();
        case 38: return call_ledger_last_time();
        case 39: return call_ledger_last_hash();
        case 40: return call_ledger_nonce();
        case 41: return call_ledger_keylet();
        case 42: return call_hook_account();
        case 43: return call_hook_hash();
        case 44: return call_hook_param_set();
        case 45: return call_hook_param();
        case 46: return call_hook_again();
        case 47: return call_hook_skip();
        case 48: return call_hook_pos();
        case 49: return call_slot();
        case 50: return call_slot_clear();
        case 51: return call_slot_count();
        case 52: return call_slot_set();
        case 53: return call_slot_size();
        case 54: return call_slot_subarray();
        case 55: return call_slot_subfield();
        case 56: return call_slot_type();
        case 57: return call_slot_float();
        case 58: return call_state_set();
        case 59: return call_state_foreign_set();
        case 60: return call_state();
        case 61: return call_state_foreign();
        case 62: return call_trace();
        case 63: return call_trace_num();
        case 64: return call_trace_float();
        case 65: return call_otxn_burden();
        case 66: return call_otxn_field();
        case 67: return call_otxn_generation();
        case 68: return call_otxn_id();
        case 69: return call_otxn_type();
        case 70: return call_otxn_slot();
        case 71: return call_otxn_param();
        case 72: return call_meta_slot();
        case 73: return call_xpop_slot();
        case 74: return call_prepare();
        default: return -1;
    }
}
