#!/usr/bin/env python3
"""Generate the independent all-import Wasmtime host-adapter fixture.

The runtime catalogue comes only from hook_api.macro. This test fixture takes
the deliberately independent route: Clang parses the public hook/extern.h
declarations, generated C retains and exports one wrapper per declaration, and
wasmcc compiles the result with an explicit memory export.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[4]
EXTERN = ROOT / "hook" / "extern.h"
SOURCE = HERE / "catalogue.c"
HEADER = HERE / "catalogue_wasm.h"
MANIFEST = HERE / "manifest.json"
EXPECTED_COUNT = 75
FLAGS = ["-O2", "-Wl,--allow-undefined", "-Wl,--export-all"]


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise SystemExit("command failed: " + " ".join(command) + "\n" + result.stderr)
    return result


def walk(node: dict):
    yield node
    for child in node.get("inner", []):
        yield from walk(child)


def declarations(clang: str) -> list[dict]:
    ast = json.loads(
        run(
            [
                clang,
                "-Xclang",
                "-ast-dump=json",
                "-fsyntax-only",
                "-x",
                "c",
                str(EXTERN),
            ]
        ).stdout
    )
    result = []
    for node in walk(ast):
        if node.get("kind") != "FunctionDecl" or node.get("storageClass") != "extern":
            continue
        function_type = node["type"]["qualType"]
        return_type = function_type.split(" (", 1)[0]
        parameters = [
            child["type"]["qualType"]
            for child in node.get("inner", [])
            if child.get("kind") == "ParmVarDecl"
        ]
        if return_type not in {"int32_t", "int64_t"} or any(
            item not in {"uint32_t", "int32_t", "uint64_t", "int64_t"}
            for item in parameters
        ):
            raise SystemExit(
                f"unsupported public Hook ABI declaration: {node['name']} {function_type}"
            )
        result.append(
            {
                "name": node["name"],
                "return": return_type,
                "parameters": parameters,
            }
        )
    if len(result) != EXPECTED_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_COUNT} public Hook declarations, found {len(result)}"
        )
    names = [item["name"] for item in result]
    if len(names) != len(set(names)):
        raise SystemExit("duplicate public Hook declaration")
    return result


def render_source(items: list[dict]) -> bytes:
    lines = [
        "/* Generated by generate.py from hook/extern.h. Do not edit. */",
        '#include "extern.h"',
        "",
        "#define RAW_EXPORT __attribute__((noinline, used))",
        "",
    ]
    for index, item in enumerate(items):
        values = ["0"] * len(item["parameters"])
        if item["name"] == "_g":
            values[1] = "1"
        arguments = ", ".join(
            f"({kind}){value}"
            for kind, value in zip(item["parameters"], values, strict=True)
        )
        wrapper = f"call_{item['name']}"
        lines.extend(
            [
                "RAW_EXPORT",
                f"{item['return']} {wrapper}(void)",
                "{",
                f"    return {item['name']}({arguments});",
                "}",
                "",
            ]
        )
    lines.extend(
        [
            "RAW_EXPORT",
            "int32_t call__g_rollback(void)",
            "{",
            "    return _g((uint32_t)0, (uint32_t)0);",
            "}",
            "",
        ]
    )
    lines.extend(
        [
            "RAW_EXPORT",
            "int64_t hook(uint32_t selector)",
            "{",
            "    switch (selector)",
            "    {",
        ]
    )
    for index, _item in enumerate(items):
        lines.append(f"        case {index}: return call_{_item['name']}();")
    lines.extend(["        default: return -1;", "    }", "}", ""])
    return "\n".join(lines).encode()


def render_header(wasm: bytes, items: list[dict]) -> bytes:
    values = []
    for offset in range(0, len(wasm), 11):
        chunk = ", ".join(f"0x{value:02X}U" for value in wasm[offset : offset + 11])
        values.append(f"    {chunk},")
    names = [f'    "{item["name"]}",' for item in items]
    text = [
        "// Generated by generate.py. Do not edit.",
        "#ifndef XAHAU_TEST_RAW_HOOK_CATALOGUE_WASM_H_INCLUDED",
        "#define XAHAU_TEST_RAW_HOOK_CATALOGUE_WASM_H_INCLUDED",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace ripple::test::raw_hook_catalogue_fixture {",
        f"inline constexpr std::array<std::uint8_t, {len(wasm)}> wasm{{{{",
        *values,
        "}};",
        f"inline constexpr std::array<std::string_view, {len(items)}> names{{{{",
        *names,
        "}};",
        "}  // namespace ripple::test::raw_hook_catalogue_fixture",
        "",
        "#endif",
        "",
    ]
    return "\n".join(text).encode()


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compiler_identity(command: str) -> str:
    probe = run([command, "-v", "-E", "-x", "c", "/dev/null"])
    return next(line for line in probe.stderr.splitlines() if "clang version" in line)


def generate(clang: str, wasmcc: str) -> dict[Path, bytes]:
    items = declarations(clang)
    source = render_source(items)
    with tempfile.TemporaryDirectory(prefix="xahau-raw-hook-catalogue-") as tmp:
        source_path = Path(tmp) / "catalogue.c"
        wasm_path = Path(tmp) / "catalogue.wasm"
        source_path.write_bytes(source)
        command = [
            wasmcc,
            "-x",
            "c",
            str(source_path),
            "-I",
            str(EXTERN.parent),
            "-o",
            str(wasm_path),
            *FLAGS,
        ]
        run(command)
        wasm = wasm_path.read_bytes()

    manifest = {
        "schema": 1,
        "declaration_source": "hook/extern.h",
        "declaration_sha256": sha256(EXTERN.read_bytes()),
        "declaration_count": len(items),
        "ast_parser": compiler_identity(clang),
        "wasm_compiler": compiler_identity(wasmcc),
        "wasmcc_flags": FLAGS,
        "source_sha256": sha256(source),
        "wasm_sha256": sha256(wasm),
        "wasm_size": len(wasm),
    }
    return {
        SOURCE: source,
        HEADER: render_header(wasm, items),
        MANIFEST: (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--clang", default=os.environ.get("HOOK_AST_CLANG"))
    parser.add_argument("--wasmcc", default=os.environ.get("WASMCC", "wasmcc"))
    args = parser.parse_args()

    outputs = generate(args.clang or args.wasmcc, args.wasmcc)
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_bytes(content)
    if stale:
        raise SystemExit("stale raw Hook catalogue fixture: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
