export XAHAUD_REPO="git@github.com:Xahau/xahaud.git"
export XAHAUD_NAME="xahaud"

export LLVM_VERSION=14
export PROTOBUF_VERSION=3.20.0
export WASMEDGE_VERSION=0.11.2
export BOOST_VERSION=1.86.0

export WASMEDGE_FOLDER_NAME="WasmEdge-$WASMEDGE_VERSION"
export PROTOBUF_FOLDER_NAME="protobuf-$PROTOBUF_VERSION"
export BOOST_FOLDER_NAME="boost_$(echo "$BOOST_VERSION" | sed 's/\./_/g')"

export BOOST_DIR="$XAHAUD_DEPS/$BOOST_FOLDER_NAME"
export BOOST_ROOT="$XAHAUD_DEPS/$BOOST_FOLDER_NAME"
export BOOST_LIBRARY_DIRS="$XAHAUD_DEPS/$BOOST_FOLDER_NAME/libs"
export BOOST_INCLUDE_DIR="$XAHAUD_DEPS/$BOOST_FOLDER_NAME/boost"
export BOOST_CXXFLAGS="${BOOST_CXXFLAGS:-} -DBOOST_ASIO_HAS_STD_INVOKE_RESULT"

export LLVM_PREFIX=`brew --prefix llvm@$LLVM_VERSION`
export LLVM_DIR="$LLVM_PREFIX/lib/cmake/llvm"
export LLVM_LIBRARY_DIR="$LLVM_PREFIX/lib"
export LLD_DIR="$LLVM_PREFIX/lib/cmake/lld"

export CC=clang
export CXX=clang++
export LDFLAGS="${LDFLAGS:-} -L$BOOST_LIBRARY_DIRS -L$LLVM_PREFIX/lib"
export CPPFLAGS="${CPPFLAGS:-} -I$XAHAUD_DEPS/$BOOST_FOLDER_NAME/include -I$LLVM_PREFIX/include"
export CFLAGS="${CFLAGS:-} -DBOOST_ASIO_HAS_STD_INVOKE_RESULT"
export CXXFLAGS="${CXXFLAGS:-} -DBOOST_ASIO_HAS_STD_INVOKE_RESULT"

