#!/bin/bash
rm -r wasmjs && mkdir wasmjs
echo '
//This file is generated by build_test_hooks.h
#ifndef SETHOOK_JSWASM_INCLUDED
#define SETHOOK_JSWASM_INCLUDED
#include <map>
#include <stdint.h>
#include <string>
#include <vector>
namespace ripple {
namespace test {
std::map<std::string, std::vector<uint8_t>> jswasm = {' > SetJSHook_tmp_wasm.h
COUNTER="0"
cat SetJSHook_test.cpp | tr '\n' '\f' |
        ggrep -Po 'R"\[test\.hook\](.*?)\[test\.hook\]"' | 
        gsed -E 's/R"\[test\.hook\]\(//g' | 
        gsed -E 's/\)\[test\.hook\]"[\f \t]*/\/*end*\//g' | 
        while read -r line
        do
            echo "/* ==== WASM: $COUNTER ==== */" >> SetJSHook_tmp_wasm.h
            echo -n '{ R"[test.hook](' >> SetJSHook_tmp_wasm.h
            cat <<< $line | gsed -E 's/.{7}$//g' | tr -d '\n' | tr '\f' '\n' >> SetJSHook_tmp_wasm.h
            echo ')[test.hook]",' >> SetJSHook_tmp_wasm.h
            echo "{" >> SetJSHook_tmp_wasm.h
            WAT=`ggrep -Eo '\(module' <<< $line | wc -l`
            if [ "$WAT" -eq "0" ]
            then
                tr '\f' '\n' <<< $line >> wasmjs/test-$COUNTER-gen.js
                ./build-js-carray.sh wasmjs/test-$COUNTER-gen.js >> SetJSHook_tmp_wasm.h
            else
                echo "Compilation error ^"
                exit 1
            fi
            if [ "$?" -gt "0" ]
            then
                echo "Compilation error ^"
                exit 1
            fi
            echo '}},' >> SetJSHook_tmp_wasm.h
            echo >> SetJSHook_tmp_wasm.h
            COUNTER=`echo $COUNTER + 1 | bc`
        done
echo '};
}
}
#endif' >> SetJSHook_tmp_wasm.h
