#!/bin/bash
CURRENT=$(cd $(dirname $0);pwd)
OUTPUT_FILE="SetJSHook_wasm.h"
WASMJS_DIR="$CURRENT/../../../generated/wasmjs"
mkdir -p $WASMJS_DIR
echo '
//This file is generated by build_test_hooks.h
#ifndef SETHOOK_JSWASM_INCLUDED
#define SETHOOK_JSWASM_INCLUDED
#include <map>
#include <stdint.h>
#include <string>
#include <vector>
namespace ripple {
namespace test {
std::map<std::string, std::vector<uint8_t>> jswasm = {' > $OUTPUT_FILE
COUNTER="0"
cat SetJSHook_test.cpp | tr '\n' '\f' |
        ggrep -Po 'R"\[test\.hook\](.*?)\[test\.hook\]"' | 
        gsed -E 's/R"\[test\.hook\]\(//g' | 
        gsed -E 's/\)\[test\.hook\]"[\f \t]*/\/*end*\//g' | 
        while read -r line
        do
            echo "/* ==== WASM: $COUNTER ==== */" >> $OUTPUT_FILE
            echo -n '{ R"[test.hook](' >> $OUTPUT_FILE
            cat <<< "$line" | gsed -E 's/.{7}$//g' | tr -d '\n' | tr '\f' '\n' >> $OUTPUT_FILE
            echo ')[test.hook]",' >> $OUTPUT_FILE
            echo "{" >> $OUTPUT_FILE
            WAT=`ggrep -Eo '\(module' <<< "$line" | wc -l`
            if [ "$WAT" -eq "0" ]
            then
                tr '\f' '\n' <<< "$line" > "$WASMJS_DIR/test-$COUNTER-gen.js"
                ./build-js-carray.sh "$WASMJS_DIR/test-$COUNTER-gen.js" >> $OUTPUT_FILE
            else
                echo "Compilation error ^"
                exit 1
            fi
            if [ "$?" -gt "0" ]
            then
                echo "Compilation error ^"
                exit 1
            fi
            echo '}},' >> $OUTPUT_FILE
            echo >> $OUTPUT_FILE
            COUNTER=`echo $COUNTER + 1 | bc`
        done
echo '};
}
}
#endif' >> $OUTPUT_FILE
