// Generated by build_test_jshooks.py - DO COMMIT THIS FILE
// Last updated: 2025-07-31 16:32:45
//
// This file provides a registry of all JS test hooks.
// Individual compiled hooks are in build/jshooks/generated/

#ifndef SETHOOK_JSWASM_INCLUDED
#define SETHOOK_JSWASM_INCLUDED

#include <map>
#include <stdint.h>
#include <string>
#include <vector>

namespace ripple {
namespace test {

// Map of all JS test hooks - populated at compile time
std::map<std::string, std::vector<uint8_t>> jswasm = {
#include "generated/test.hook.0305445f.inc"  // otxn_param
#include "generated/test.hook.10ab0748.inc"  // float_set
#include "generated/test.hook.142f641f.inc"  // sto_from_json
#include "generated/test.hook.18e0c322.inc"  // util_keylet
#include "generated/test.hook.199f826f.inc"  // ledger_last_time
#include "generated/test.hook.1a483e9c.inc"  // rollback_wasm shared fixture
#include "generated/test.hook.1d840b9f.inc"  // sto_subfield
#include "generated/test.hook.1e16dd4a.inc"  // slot
#include "generated/test.hook.25b3ce01.inc"  // state_foreign 2
#include "generated/test.hook.2634e38b.inc"  // meta_slot
#include "generated/test.hook.290f5014.inc"  // sto_emplace
#include "generated/test.hook.2c6ecbab.inc"  // trace
#include "generated/test.hook.2c977017.inc"  // float_negate
#include "generated/test.hook.2dca46e2.inc"  // sto_to_json
#include "generated/test.hook.2efe8db7.inc"  // state_foreign
#include "generated/test.hook.30908fb9.inc"  // float_compare
#include "generated/test.hook.31c07899.inc"  // otxn_json
#include "generated/test.hook.331d7b29.inc"  // hook_param
#include "generated/test.hook.36618b26.inc"  // float_one
#include "generated/test.hook.36ca6430.inc"  // etxn_details
#include "generated/test.hook.396798f3.inc"  // hook_param_set
#include "generated/test.hook.3abad299.inc"  // float_sto_set
#include "generated/test.hook.3e88fc2e.inc"  // state_set 4
#include "generated/test.hook.457f6fcb.inc"  // state
#include "generated/test.hook.46846897.inc"  // float_sto
#include "generated/test.hook.4719b491.inc"  // hook_skip 2
#include "generated/test.hook.4c6bf09d.inc"  // hook_pos
#include "generated/test.hook.4c97ae4e.inc"  // float_sign
#include "generated/test.hook.4f65963b.inc"  // state_set 5
#include "generated/test.hook.555ced04.inc"  // slot_json
#include "generated/test.hook.599069d5.inc"  // otxn_id
#include "generated/test.hook.5d3a64c4.inc"  // hook_param_set 2
#include "generated/test.hook.5f4f67b6.inc"  // emit
#include "generated/test.hook.60d0b0e4.inc"  // hook_hash 2
#include "generated/test.hook.66eb459a.inc"  // float_int
#include "generated/test.hook.6728250b.inc"  // etxn_reserve
#include "generated/test.hook.677d5266.inc"  // hook_hash
#include "generated/test.hook.68943bb2.inc"  // state_foreign_set 2
#include "generated/test.hook.6eec67ee.inc"  // slot_clear
#include "generated/test.hook.7071c017.inc"  // hook_account
#include "generated/test.hook.7179c162.inc"  // slot_size
#include "generated/test.hook.739ba2a9.inc"  // etxn_fee_base
#include "generated/test.hook.778177cb.inc"  // illegalfunc_wasm shared fixture
#include "generated/test.hook.792b9aff.inc"  // sto_subarray
#include "generated/test.hook.7940dca6.inc"  // float_log
#include "generated/test.hook.79f929db.inc"  // float_invert
#include "generated/test.hook.7c9f50c0.inc"  // slot_subfield
#include "generated/test.hook.814c1767.inc"  // ledger_keylet
#include "generated/test.hook.847f65e2.inc"  // hook_skip
#include "generated/test.hook.84a2571a.inc"  // hook_again
#include "generated/test.hook.85a574bf.inc"  // otxn_field
#include "generated/test.hook.8ab69a64.inc"  // otxn_type
#include "generated/test.hook.8d8ea78d.inc"  // fee_base
#include "generated/test.hook.90413179.inc"  // slot_count
#include "generated/test.hook.95f46eaa.inc"  // float_root
#include "generated/test.hook.9f180243.inc"  // state_set 6
#include "generated/test.hook.9f44d362.inc"  // state_foreign_set
#include "generated/test.hook.a276d4a8.inc"  // sto_validate
#include "generated/test.hook.a70f7944.inc"  // accept2_wasm shared fixture
#include "generated/test.hook.aa9fa906.inc"  // ledger_nonce
#include "generated/test.hook.aac32d2a.inc"  // slot_type
#include "generated/test.hook.ad52e99c.inc"  // long_wasm shared fixture
#include "generated/test.hook.ae24a3f2.inc"  // float_divide
#include "generated/test.hook.b7061fdf.inc"  // util_verify
#include "generated/test.hook.b8263664.inc"  // state_foreign_set 3
#include "generated/test.hook.b859c03d.inc"  // etxn_nonce
#include "generated/test.hook.b8786e8a.inc"  // state 2
#include "generated/test.hook.b8bec9eb.inc"  // otxn_slot
#include "generated/test.hook.bc420161.inc"  // state_set 2
#include "generated/test.hook.ce4f3f36.inc"  // float_mulratio
#include "generated/test.hook.ce530c61.inc"  // sto_erase
#include "generated/test.hook.d6c36709.inc"  // accept_wasm shared fixture
#include "generated/test.hook.d6e25565.inc"  // ledger_seq
#include "generated/test.hook.d7fb6f7a.inc"  // makestate_wasm shared fixture
#include "generated/test.hook.dff0cc8a.inc"  // float_multiply
#include "generated/test.hook.e2700aa8.inc"  // util_raddr
#include "generated/test.hook.e3a6ad48.inc"  // slot_subarray
#include "generated/test.hook.e47bc20c.inc"  // slot_float
#include "generated/test.hook.e56c5e25.inc"  // float_sum
#include "generated/test.hook.e6430631.inc"  // JS Date
#include "generated/test.hook.e85930f6.inc"  // state_set
#include "generated/test.hook.e9b994bf.inc"  // util_sha512h
#include "generated/test.hook.efe68386.inc"  // util_accid
#include "generated/test.hook.f5cc1f27.inc"  // slot_set
#include "generated/test.hook.f833328d.inc"  // float_mantissa
#include "generated/test.hook.f8ad628e.inc"  // ledger_last_hash
#include "generated/test.hook.ff43d8f7.inc"  // state_set 3
#include "generated/test.hook.ff6ba5cb.inc"  // xpop_slot
};

}  // namespace test
}  // namespace ripple

#endif
