#!/usr/bin/env python3
"""Project the sealed QuickJS provider WASM into a C++ translation unit.

The bytes are re-verified against the manifest's SHA-256 and size so a stale
or swapped provider cannot be embedded silently. The output defines
hook::embeddedQuickJSProvider(); with --absent it defines the empty span for
builds whose bundle directory carries no provider binary.
"""
import argparse
import hashlib
import sys

CHUNK = 64


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True)
    parser.add_argument("--provider")
    parser.add_argument("--sha256")
    parser.add_argument("--size", type=int)
    parser.add_argument("--absent", action="store_true")
    args = parser.parse_args()

    if args.absent:
        body = (
            "std::span<std::uint8_t const>\n"
            "embeddedQuickJSProvider()\n"
            "{\n"
            "    return {};\n"
            "}\n"
        )
        provenance = "no provider binary was present in the bundle directory"
    else:
        if not (args.provider and args.sha256 and args.size is not None):
            parser.error("--provider, --sha256 and --size are required")
        with open(args.provider, "rb") as handle:
            data = handle.read()
        digest = hashlib.sha256(data).hexdigest()
        if digest != args.sha256.lower():
            print(
                f"provider SHA-256 {digest} does not match manifest {args.sha256}",
                file=sys.stderr,
            )
            return 1
        if len(data) != args.size:
            print(
                f"provider size {len(data)} does not match manifest {args.size}",
                file=sys.stderr,
            )
            return 1
        # One string literal, every byte escaped: \xNN cannot run into the
        # next byte because the next character is always a backslash.
        lines = []
        for offset in range(0, len(data), CHUNK):
            chunk = data[offset : offset + CHUNK]
            lines.append('    "' + "".join(f"\\x{b:02x}" for b in chunk) + '"')
        body = (
            "namespace {\n"
            "\n"
            "constexpr char const sealedProvider[] =\n"
            + "\n".join(lines)
            + ";\n"
            "\n"
            "static_assert(\n"
            f"    sizeof(sealedProvider) - 1 == {len(data)},\n"
            '    "embedded provider size disagrees with its manifest");\n'
            "\n"
            "}  // namespace\n"
            "\n"
            "std::span<std::uint8_t const>\n"
            "embeddedQuickJSProvider()\n"
            "{\n"
            "    return {\n"
            "        reinterpret_cast<std::uint8_t const*>(sealedProvider),\n"
            "        sizeof(sealedProvider) - 1};\n"
            "}\n"
        )
        provenance = f"{args.provider} sha256={digest} size={len(data)}"

    text = (
        "// Generated by cmake/EmbedQuickJSProvider.py; do not edit.\n"
        f"// Source: {provenance}\n"
        "#include <xrpld/app/hook/QuickJSHookRuntime.h>\n"
        "#include <cstdint>\n"
        "#include <span>\n"
        "\n"
        "namespace hook {\n"
        "\n" + body + "\n"
        "}  // namespace hook\n"
    )
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
