cmake_minimum_required(VERSION 3.16)

foreach(_required
    INPUT
    VALUES_INPUT
    EXPECTED_SHA256
    EXPECTED_SIZE
    EXPECTED_VALUES_SHA256
    OUTPUT)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "EmbedQuickJSProvider.cmake requires ${_required}")
  endif()
endforeach()

if(NOT EXISTS "${VALUES_INPUT}")
  message(FATAL_ERROR "Missing preprojected QuickJS values: ${VALUES_INPUT}")
endif()
file(SHA256 "${VALUES_INPUT}" _actual_values_sha256)
if(NOT _actual_values_sha256 STREQUAL EXPECTED_VALUES_SHA256)
  message(FATAL_ERROR
    "Preprojected QuickJS values do not match the sealed receipt")
endif()

file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" _script_sha256)
if(EXISTS "${INPUT}")
  file(SHA256 "${INPUT}" _actual_sha256)
  file(SIZE "${INPUT}" _actual_size)
  if(NOT _actual_sha256 STREQUAL EXPECTED_SHA256 OR
      NOT "${_actual_size}" STREQUAL "${EXPECTED_SIZE}")
    message(FATAL_ERROR
      "QuickJS provider WASM does not match the sealed receipt: "
      "sha256=${_actual_sha256} size=${_actual_size}")
  endif()
  set(_input_state "${_actual_sha256}:${_actual_size}")
else()
  set(_input_state absent)
endif()

set(_stamp "${_script_sha256}:${_actual_values_sha256}:${_input_state}")
set(_stamp_file "${OUTPUT}.stamp")
if(EXISTS "${OUTPUT}" AND EXISTS "${_stamp_file}")
  file(READ "${_stamp_file}" _old_stamp)
  if(_old_stamp STREQUAL _stamp)
    return()
  endif()
endif()

get_filename_component(_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
set(_temporary "${OUTPUT}.tmp")
file(WRITE "${_temporary}" [=[// Generated by cmake/EmbedQuickJSProvider.cmake; do not edit.
#include <xrpld/app/hook/QuickJSHookRuntime.h>

#include <cstdint>
#include <span>

namespace hook {

]=])

if(EXISTS "${INPUT}")
  file(APPEND "${_temporary}" "namespace {\n\nconstexpr char const sealedProvider[] =\n")

  # Read 16 KiB at a time, formatting it as adjacent 64-byte C++ string
  # literals. This avoids holding the 5 MiB escaped representation in CMake.
  set(_byte_offset 0)
  while(_byte_offset LESS _actual_size)
    math(EXPR _bytes_left "${_actual_size} - ${_byte_offset}")
    if(_bytes_left GREATER 16384)
      set(_bytes_to_read 16384)
    else()
      set(_bytes_to_read "${_bytes_left}")
    endif()
    file(READ "${INPUT}" _hex
      OFFSET "${_byte_offset}" LIMIT "${_bytes_to_read}" HEX)
    string(LENGTH "${_hex}" _hex_length)
    set(_hex_offset 0)
    set(_block "")
    while(_hex_offset LESS _hex_length)
      math(EXPR _hex_left "${_hex_length} - ${_hex_offset}")
      if(_hex_left GREATER 128)
        set(_line_length 128)
      else()
        set(_line_length "${_hex_left}")
      endif()
      string(SUBSTRING "${_hex}" "${_hex_offset}" "${_line_length}" _line)
      string(REGEX REPLACE "([0-9a-f][0-9a-f])" "\\\\x\\1" _line "${_line}")
      string(APPEND _block "    \"${_line}\"\n")
      math(EXPR _hex_offset "${_hex_offset} + ${_line_length}")
    endwhile()
    file(APPEND "${_temporary}" "${_block}")
    math(EXPR _byte_offset "${_byte_offset} + ${_bytes_to_read}")
  endwhile()

  file(APPEND "${_temporary}" [=[;

static_assert(
    sizeof(sealedProvider) - 1 == ]=] "${_actual_size}" [=[,
    "embedded provider size disagrees with its receipt");

}  // namespace

std::span<std::uint8_t const>
embeddedQuickJSProvider()
{
    return {
        reinterpret_cast<std::uint8_t const*>(sealedProvider),
        sizeof(sealedProvider) - 1};
}
]=])
else()
  message(WARNING
    "No QuickJS provider WASM at ${INPUT}; the daemon will refuse to start")
  file(APPEND "${_temporary}" [=[std::span<std::uint8_t const>
embeddedQuickJSProvider()
{
    return {};
}
]=])
endif()

file(APPEND "${_temporary}" "\n}  // namespace hook\n")
file(RENAME "${_temporary}" "${OUTPUT}")
file(WRITE "${_stamp_file}.tmp" "${_stamp}")
file(RENAME "${_stamp_file}.tmp" "${_stamp_file}")
