name: Build using Docker

on:
  push:
    branches: [ "dev", "candidate", "release", "jshooks" ]
  pull_request:
    branches: [ "dev", "candidate", "release", "jshooks" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: [self-hosted, vanity]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
  checkpatterns:
    runs-on: [self-hosted, vanity]
    needs: checkout
    steps:
      - name: Check for suspicious patterns
        run: /bin/bash suspicious_patterns.sh
  build:
    # This runner only runs one workflow at a time, and queues them
    runs-on: [self-hosted, vanity]
    needs: checkpatterns
    steps:
      - name: Set Cleanup Script Path
        run: echo "JOB_CLEANUP_SCRIPT=$(mktemp)" >> $GITHUB_ENV

      - name: Build using Docker
        run: /bin/bash release-builder.sh

      - name: Stop Container (Cleanup)
        if: always()
        run: |
          echo "Running cleanup script: $JOB_CLEANUP_SCRIPT"
          /bin/bash "$JOB_CLEANUP_SCRIPT"
          rm -f "$JOB_CLEANUP_SCRIPT"

  tests:
    runs-on: [self-hosted, vanity]
    needs: build
    steps:
      - name: Unit tests
        run: /bin/bash docker-unit-tests.sh
